package org.datum.model;

public enum SubRegion {
	SOUTHERN_ASIA,
	WESTERN_ASIA,
	SOUTH_EASTERN_ASIA,
	WESTERN_EUROPE,
	EASTERN_EUROPE,
	SOUTHERN_EUROPE,
	NORTHERN_EUROPE,
	POLYNESIA,
	MELANESIA,
	AUSTRALIA_AND_NEW_ZEALAND,
	MIDDLE_AFRICA,
	SUB_SAHARAN_AFRICA,
	EASTERN_AFRICA,
	WESTERN_AFRICA,
	NORTHERN_AMERICA,
	LATIN_AMERICA_AND_THE_CARIBBEAN
}
